name: CI

on:
  # Specify the event that will trigger the workflow
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Use checkout action to check out the repository on the runner
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Python to 3.9 using setup-python action
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Run the hello_world.py python script
      - name: Run Python script
        run: |
          python3 hello_world.py